import type { ComponentType } from "react";
import {
  Camera,
  Cable,
  Gamepad2,
  HardDrive,
  Keyboard,
  Mic2,
  Mouse,
  Network,
  Printer,
  Projector,
  Router,
  ScanLine,
  Speaker,
  Usb,
} from "lucide-react";

export interface PeripheralCategory {
  id: number;
  slug: string;
  name: string;
  summary: string;
  specs: string[];
  icon: ComponentType<{ size?: number; strokeWidth?: number }>;
}

export const peripheralCategories: PeripheralCategory[] = [
  {
    id: 1,
    slug: "keyboard",
    name: "Keyboard",
    summary: "Layouts, switches, keycaps and connection options.",
    specs: [
      "Layout",
      "Switch type",
      "Keycap material",
      "Connectivity",
      "Polling rate",
      "Backlighting",
      "Rollover",
      "Programmability",
    ],
    icon: Keyboard,
  },
  {
    id: 2,
    slug: "mouse",
    name: "Mouse",
    summary: "Sensors, tracking performance, weight and ergonomics.",
    specs: [
      "DPI range",
      "Sensor model",
      "Weight",
      "Switch type",
      "Polling rate",
      "Grip style",
      "Connectivity",
      "Battery life",
    ],
    icon: Mouse,
  },
  {
    id: 3,
    slug: "printer",
    name: "Printer",
    summary: "Print technology, speed, media handling and running cost.",
    specs: [
      "Print technology",
      "Pages per minute",
      "Duplex printing",
      "Print resolution",
      "Paper capacity",
      "Connectivity",
      "Supported media sizes",
      "Duty cycle",
    ],
    icon: Printer,
  },
  {
    id: 4,
    slug: "scanner",
    name: "Scanner",
    summary: "Resolution, document handling, speed and color accuracy.",
    specs: [
      "Optical resolution",
      "Scanner type",
      "Automatic document feeder",
      "Scanning speed",
      "Color depth",
      "Maximum document size",
      "Connectivity",
      "Duplex scanning",
    ],
    icon: ScanLine,
  },
  {
    id: 5,
    slug: "camera",
    name: "Camera",
    summary: "Sensors, lenses, resolution and video performance.",
    specs: [
      "Sensor size",
      "Photo resolution",
      "Video resolution",
      "Maximum frame rate",
      "Lens mount",
      "Autofocus system",
      "Image stabilization",
      "Connectivity",
    ],
    icon: Camera,
  },
  {
    id: 6,
    slug: "microphone",
    name: "Microphone",
    summary: "Pickup pattern, sensitivity, connection and recording quality.",
    specs: [
      "Polar pattern",
      "Connection type",
      "Frequency response",
      "Sensitivity",
      "Sample rate",
      "Bit depth",
      "Self-noise",
      "Monitoring output",
    ],
    icon: Mic2,
  },
  {
    id: 7,
    slug: "projector",
    name: "Projector",
    summary: "Brightness, image size, throw distance and display quality.",
    specs: [
      "Brightness",
      "Throw ratio",
      "Native resolution",
      "Contrast ratio",
      "Light source",
      "Refresh rate",
      "Maximum image size",
      "Input ports",
    ],
    icon: Projector,
  },
  {
    id: 8,
    slug: "speaker",
    name: "Speaker",
    summary: "Channels, power, frequency response and connection options.",
    specs: [
      "Channel configuration",
      "Power output",
      "Frequency response",
      "Driver size",
      "Connectivity",
      "Impedance",
      "Signal-to-noise ratio",
      "Enclosure type",
    ],
    icon: Speaker,
  },
  {
    id: 9,
    slug: "external-hdd",
    name: "External HDD",
    summary: "Portable storage capacity, transfer speed and durability.",
    specs: [
      "Capacity",
      "Read speed",
      "Write speed",
      "Interface",
      "Drive speed",
      "Form factor",
      "Power source",
      "Encryption support",
    ],
    icon: HardDrive,
  },
  {
    id: 10,
    slug: "modem",
    name: "Modem",
    summary: "Broadband standards, channels, speed and provider compatibility.",
    specs: [
      "DOCSIS standard",
      "Downstream channels",
      "Upstream channels",
      "Maximum download speed",
      "Maximum upload speed",
      "Ethernet ports",
      "Voice support",
      "Provider compatibility",
    ],
    icon: Cable,
  },
  {
    id: 11,
    slug: "router",
    name: "Router",
    summary: "Wireless standards, bands, coverage and network controls.",
    specs: [
      "Wi-Fi standard",
      "Frequency bands",
      "Coverage",
      "Maximum wireless speed",
      "Ethernet ports",
      "Antenna configuration",
      "Security standard",
      "Mesh support",
    ],
    icon: Router,
  },
  {
    id: 12,
    slug: "switch",
    name: "Switch",
    summary: "Port count, speed, power delivery and management features.",
    specs: [
      "Port count",
      "Port speed",
      "PoE support",
      "PoE budget",
      "Managed or unmanaged",
      "Switching capacity",
      "VLAN support",
      "Uplink ports",
    ],
    icon: Network,
  },
  {
    id: 13,
    slug: "usb",
    name: "USB",
    summary: "Version, capacity, connector type and transfer performance.",
    specs: [
      "USB version",
      "Capacity",
      "Connector type",
      "Read speed",
      "Write speed",
      "Form factor",
      "Encryption",
      "Operating-system support",
    ],
    icon: Usb,
  },
  {
    id: 14,
    slug: "game-controller",
    name: "Game Controller",
    summary: "Layout, compatibility, connectivity and control technology.",
    specs: [
      "Button layout",
      "Connectivity",
      "Platform compatibility",
      "Hall-effect sticks",
      "Trigger technology",
      "Haptic feedback",
      "Battery life",
      "Programmable controls",
    ],
    icon: Gamepad2,
  },
];

export const getCategory = (idOrSlug: string | number) =>
  peripheralCategories.find(
    (category) =>
      category.id === Number(idOrSlug) || category.slug === String(idOrSlug),
  );
